<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Prof.&nbsp;Denise B. Ferrari">

<title>GED-16: Análise de Regressão</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="GED16_AULA07_Pratica_files/libs/clipboard/clipboard.min.js"></script>
<script src="GED16_AULA07_Pratica_files/libs/quarto-html/quarto.js"></script>
<script src="GED16_AULA07_Pratica_files/libs/quarto-html/popper.min.js"></script>
<script src="GED16_AULA07_Pratica_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GED16_AULA07_Pratica_files/libs/quarto-html/anchor.min.js"></script>
<link href="GED16_AULA07_Pratica_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GED16_AULA07_Pratica_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GED16_AULA07_Pratica_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GED16_AULA07_Pratica_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GED16_AULA07_Pratica_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">GED-16: Análise de Regressão</h1>
<p class="subtitle lead">AULA07: Prática (1o. semestre/2023)</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Prof.&nbsp;Denise B. Ferrari </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">19 de abril de 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<hr>
<p>Abalone é um tipo de molusco que vive em águas marinhas costeiras em diversas regiões do globo. A concha do abalone apresenta tamanho que varia entre 10 a 25cm e sua coloração interior iridescente nacarada é muito valorizada na confecção de jóias e ornamentos; além disso, a carne do animal é considerada uma iguaria em muitos países. Devido ao seu alto valor comercial e consequente pesca excessiva, além da degradação de seu habitat pela ação humana, diversas espécies de abalone atualmente correm risco de extinção. Existem mais de 100 espécies de abalone ao redor do mundo, das quais cerca de 15 são produzidas por meio de aquicultura. Determinar a idade do abalone de maneira acurada é importante tanto em termos comerciais (o valor comercial do abalone está associado à sua idade) bem como em termos ambientais (condições ambientais podem afetar a saúde do animal). A idade do animal pode ser determinada a partir da contagem do número de anéis na concha, utilizando um microscópio, a partir de um procedimento delicado e trabalhoso.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/abalone.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Abalone (Image by <a href="https://pixabay.com/users/lisaleo-3220940/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4919586">Lisa Yount</a> from <a href="https://pixabay.com//?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=4919586">Pixabay</a>)</figcaption><p></p>
</figure>
</div>
<p>Os dados disponíveis no arquivo <code>data/abalone/abalone.data</code> foram obtidos no <a href="https://archive.ics.uci.edu/ml/datasets/Abalone">UCI Machine Learning Repository</a> e são bastante utilizados na investigação de métodos de Machine Learning. Tais dados foram coletados a partir do estudo original:</p>
<p>Warwick J Nash, Tracy L Sellers, Simon R Talbot, Andrew J Cawthorn and Wes B Ford (1994) “The Population Biology of Abalone (<em>Haliotis</em> species) in Tasmania. I. Blacklip Abalone (<em>H. rubra</em>) from the North Coast and Islands of Bass Strait”, Sea Fisheries Division, Technical Report No.&nbsp;48 (ISSN 1034-3288).</p>
<p>O principal objetivo do projeto era determinar a idade do molusco a partir de medidas físicas do animal mais fáceis de serem obtidas. Os dados originais foram pré-processados no sentido de remover observações faltantes e os valores das variáveis contínuas foram dividos por 200. Há um total de 4177 observações coletadas para 9 variáveis:</p>
<ol type="1">
<li><code>sex</code>: sexo do animal (M, F, I)</li>
<li><code>length</code>: maior comprimento da concha (mm)</li>
<li><code>diameter</code>: comprimento perpendicular à <code>length</code> (mm)</li>
<li><code>height</code>: comprimento da carne da concha (mm)</li>
<li><code>whole_w</code>: peso do animal (g)</li>
<li><code>shucked_w</code>: peso da carne (g)</li>
<li><code>viscera_w</code>: peso das vísceras (g)</li>
<li><code>shell_w</code>: peso da concha (g)</li>
<li><code>rings</code>: número de anéis (a idade é obtida somando 1.5)</li>
</ol>
<p>Mais informações a respeito dos dados podem ser obtidas no arquivo <code>data/abalone/abalone.names</code>.</p>
<hr>
<section id="análise-exploratória-de-dados" class="level1">
<h1>Análise Exploratória de Dados</h1>
<p>Conduza a análise exploratória da massa de dados <code>abalone</code>, a fim de compreender suas características principais.<br>
Voltaremos a utilizar essa massa de dados em atividades futuras.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>abalone <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/abalone/abalone.data"</span>, <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(abalone) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"sex"</span>, <span class="st">"length"</span>, <span class="st">"diameter"</span>, <span class="st">"height"</span>, <span class="st">"whole_w"</span>, <span class="st">"shucked_w"</span>, <span class="st">"viscera_w"</span>, <span class="st">"shell_w"</span>, <span class="st">"rings"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Começamos identificando a estrutura dos dados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(abalone)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [4,177 × 9] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ sex      : chr [1:4177] "M" "M" "F" "M" ...
 $ length   : num [1:4177] 0.455 0.35 0.53 0.44 0.33 0.425 0.53 0.545 0.475 0.55 ...
 $ diameter : num [1:4177] 0.365 0.265 0.42 0.365 0.255 0.3 0.415 0.425 0.37 0.44 ...
 $ height   : num [1:4177] 0.095 0.09 0.135 0.125 0.08 0.095 0.15 0.125 0.125 0.15 ...
 $ whole_w  : num [1:4177] 0.514 0.226 0.677 0.516 0.205 ...
 $ shucked_w: num [1:4177] 0.2245 0.0995 0.2565 0.2155 0.0895 ...
 $ viscera_w: num [1:4177] 0.101 0.0485 0.1415 0.114 0.0395 ...
 $ shell_w  : num [1:4177] 0.15 0.07 0.21 0.155 0.055 0.12 0.33 0.26 0.165 0.32 ...
 $ rings    : num [1:4177] 15 7 9 10 7 8 20 16 9 19 ...
 - attr(*, "spec")=
  .. cols(
  ..   X1 = col_character(),
  ..   X2 = col_double(),
  ..   X3 = col_double(),
  ..   X4 = col_double(),
  ..   X5 = col_double(),
  ..   X6 = col_double(),
  ..   X7 = col_double(),
  ..   X8 = col_double(),
  ..   X9 = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
</div>
<p>Percebemos que as variáveis já possuem nomes explicativos. Porém, percebe-se que <code>sex</code> está com tipo <code>char</code> quando deveria ser <code>Factor</code>. Vamos também obter a idade, a partir do número de anéis do Abalone, e retornar os valores contínuos para suas escalas originais (multiplicar por 200).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>abalone <span class="ot">&lt;-</span> abalone <span class="sc">%&gt;%</span> <span class="fu">mutate_at</span>(<span class="st">"sex"</span>, as.factor)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>age <span class="ot">&lt;-</span> abalone<span class="sc">$</span>rings <span class="sc">+</span> <span class="fl">1.5</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>length <span class="ot">&lt;-</span> abalone<span class="sc">$</span>length <span class="sc">*</span> <span class="dv">200</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>diameter <span class="ot">&lt;-</span> abalone<span class="sc">$</span>diameter <span class="sc">*</span> <span class="dv">200</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>height <span class="ot">&lt;-</span> abalone<span class="sc">$</span>height <span class="sc">*</span> <span class="dv">200</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>whole_w <span class="ot">&lt;-</span> abalone<span class="sc">$</span>whole_w <span class="sc">*</span> <span class="dv">200</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>shucked_w <span class="ot">&lt;-</span> abalone<span class="sc">$</span>shucked_w <span class="sc">*</span> <span class="dv">200</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>viscera_w <span class="ot">&lt;-</span> abalone<span class="sc">$</span>viscera_w <span class="sc">*</span> <span class="dv">200</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>abalone<span class="sc">$</span>shell_w <span class="ot">&lt;-</span> abalone<span class="sc">$</span>shell_w <span class="sc">*</span> <span class="dv">200</span></span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dessa forma, temos o sumário do conjunto de dados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(abalone)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> sex          length         diameter          height         whole_w     
 F:1307   Min.   : 15.0   Min.   : 11.00   Min.   :  0.0   Min.   :  0.4  
 I:1342   1st Qu.: 90.0   1st Qu.: 70.00   1st Qu.: 23.0   1st Qu.: 88.3  
 M:1528   Median :109.0   Median : 85.00   Median : 28.0   Median :159.9  
          Mean   :104.8   Mean   : 81.58   Mean   : 27.9   Mean   :165.7  
          3rd Qu.:123.0   3rd Qu.: 96.00   3rd Qu.: 33.0   3rd Qu.:230.6  
          Max.   :163.0   Max.   :130.00   Max.   :226.0   Max.   :565.1  
   shucked_w        viscera_w         shell_w           rings       
 Min.   :  0.20   Min.   :  0.10   Min.   :  0.30   Min.   : 1.000  
 1st Qu.: 37.20   1st Qu.: 18.70   1st Qu.: 26.00   1st Qu.: 8.000  
 Median : 67.20   Median : 34.20   Median : 46.80   Median : 9.000  
 Mean   : 71.87   Mean   : 36.12   Mean   : 47.77   Mean   : 9.934  
 3rd Qu.:100.40   3rd Qu.: 50.60   3rd Qu.: 65.80   3rd Qu.:11.000  
 Max.   :297.60   Max.   :152.00   Max.   :201.00   Max.   :29.000  
      age       
 Min.   : 2.50  
 1st Qu.: 9.50  
 Median :10.50  
 Mean   :11.43  
 3rd Qu.:12.50  
 Max.   :30.50  </code></pre>
</div>
</div>
<p>Percebe-se que algumas observações possuem altura zero. Avaliando essas observações:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>abalone[abalone<span class="sc">$</span>height<span class="sc">==</span><span class="dv">0</span>,]</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 10
  sex   length diameter height whole_w shucked_w viscera_w shell_w rings   age
  &lt;fct&gt;  &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 I         86       68      0    85.6      41.3      17.2    23       8   9.5
2 I         63       46      0    26.8      11.5       5.7    70.1     6   7.5</code></pre>
</div>
</div>
<p>Obtemos duas observações que não fazem sentido (altura zero e pesos diferentes de zero). Podemos retirá-las do conjunto de dados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>abalone <span class="ot">&lt;-</span> abalone[abalone<span class="sc">$</span>height<span class="sc">!=</span><span class="dv">0</span>,]</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="parte-3-construção-de-modelos" class="level2">
<h2 class="anchored" data-anchor-id="parte-3-construção-de-modelos">PARTE 3: Construção de Modelos</h2>
<p>Continuaremos considerando que a idade do abalone seja dada pela seguinte forma:</p>
<p><span class="math display">\[\textsf{age} = \textsf{rings} + \delta, \quad \delta \sim N(\mu = 1.5, \sigma = 0.5)\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">16</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>abalone <span class="ot">&lt;-</span> abalone <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># cria nova variável `age`</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age =</span> rings <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="fu">nrow</span>(abalone), <span class="at">mean =</span> <span class="fl">1.5</span>, <span class="at">sd =</span> <span class="fl">0.5</span>))</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Utilize o procedimento para construção de modelos para prever a idade de um abalone (<code>age</code>):</p>
<p><strong>Modelo I:</strong> considere como variáveis explicativas <code>length</code>, <code>diameter</code>, <code>shell_w</code> e <code>sex</code> (e transformações).</p>
<p><strong>Modelo II:</strong> considere como variáveis explicativas <code>height</code>, <code>diameter</code>, <code>shell_w</code> e <code>sex</code> (e transformações).</p>
<p>Lembre-se que os passos apropriados em análise de regressão consistem em:</p>
<p><strong>construção do modelo</strong></p>
<ol type="1">
<li>formulação do modelo<br>
</li>
<li>ajuste do modelo<br>
</li>
<li>avaliação do modelo</li>
</ol>
<p>Para a formulação dos modelos, devemos utilizar o seguinte procedimento:</p>
<ol type="1">
<li>inclusão de variáveis quantitativas (polinomiais, transformações, etc.);<br>
</li>
<li>inclusão de variáveis qualitativas;<br>
</li>
<li>inclusão de interações entre termos contendo variáveis quantitativas e qualitativas.</li>
</ol>
<p><strong>utilização do modelo</strong></p>
<ul>
<li>para realizar inferências</li>
<li>para auxiliar o processo de tomada de decisão</li>
</ul>
<p>Não esqueça de realizar análise de resíduos, inferências e validação do modelo. Forneça interpretações e discussão para os resultados obtidos.</p>
<hr>
<section id="construção-do-modelo-1" class="level3">
<h3 class="anchored" data-anchor-id="construção-do-modelo-1">Construção do Modelo 1</h3>
<section id="modelo-para-a-variável-quantitativa" class="level4">
<h4 class="anchored" data-anchor-id="modelo-para-a-variável-quantitativa">1.1) Modelo para a Variável Quantitativa</h4>
<p>A princípio, vamos construir o modelo com os termos quadráticos de cada variável explicativa quantitativa: <span class="math display">\[
  E[age] = \beta_0 + \beta_1 length + \beta_{11}length^2  + \beta_2 diameter + \beta_{22} diameter^2 +  \beta_3 shell_w + \beta_{33} shell_w^2 + \beta_{12} length \cdot diameter + \beta_{13} length \cdot shell_w + \beta_{23} diameter \cdot shell_w
\]</span> Começaremos avaliando a correlação dos termos lineares e quadráticos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(abalone<span class="sc">$</span>length, abalone<span class="sc">$</span>length<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9875853</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(abalone<span class="sc">$</span>diameter, abalone<span class="sc">$</span>diameter<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9866137</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(abalone<span class="sc">$</span>shell_w, abalone<span class="sc">$</span>shell_w<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9404706</code></pre>
</div>
</div>
<p>Percebe-se que todas as correlações são muito altas. Podemos conferir esse comportamento visualmente:</p>
<div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># diagramas de dispersão</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(abalone, <span class="fu">aes</span>(<span class="at">x =</span> length, <span class="at">y =</span> length<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Diagrama de dispersão: `length^2` x `length`"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(abalone, <span class="fu">aes</span>(<span class="at">x =</span> diameter, <span class="at">y =</span> diameter<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Diagrama de dispersão: `diameter^2` x `diameter`"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(abalone, <span class="fu">aes</span>(<span class="at">x =</span> shell_w, <span class="at">y =</span> shell_w<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Diagrama de dispersão: `shell_w^2` x `shell_w`"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="GED16_AULA07_Pratica_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="GED16_AULA07_Pratica_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="GED16_AULA07_Pratica_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>Vamos então centralizar as variáveis explicativas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># centralizando a variável explicativa</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>abalone <span class="ot">&lt;-</span> abalone <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diameter_c =</span> diameter <span class="sc">-</span> <span class="fu">mean</span>(diameter), </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">shell_w_c =</span> shell_w <span class="sc">-</span> <span class="fu">mean</span>(shell_w),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">length_c =</span> length <span class="sc">-</span> <span class="fu">mean</span>(length)) </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># novas correlações</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(abalone<span class="sc">$</span>length_c, abalone<span class="sc">$</span>length_c<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.4457653</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(abalone<span class="sc">$</span>diameter_c, abalone<span class="sc">$</span>diameter_c<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.4361484</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(abalone<span class="sc">$</span>shell_w_c, abalone<span class="sc">$</span>shell_w_c<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3903075</code></pre>
</div>
</div>
<p>Percebe-se uma redução significativa em todas as correlações. Podemos agora construir um modelo inicial com as variáveis explicativas quantitativas centralizadas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># modelo polinomial de 2a. ordem completo para as variáveis quantitativas</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>m1_quant <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> <span class="fu">I</span>(length_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(diameter_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(shell_w_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> length_c<span class="sc">*</span>shell_w_c<span class="sc">+</span> diameter_c<span class="sc">*</span>length_c <span class="sc">+</span> diameter_c<span class="sc">*</span> shell_w_c  , <span class="at">data =</span> abalone)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># resumo do modelo </span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_quant)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + 
    length_c * shell_w_c + diameter_c * length_c + diameter_c * 
    shell_w_c, data = abalone)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.7503 -1.4690 -0.3961  1.0045 16.5719 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          12.5381347  0.0590556 212.311  &lt; 2e-16 ***
I(length_c^2)        -0.0020872  0.0006210  -3.361 0.000784 ***
I(diameter_c^2)      -0.0045317  0.0013369  -3.390 0.000706 ***
I(shell_w_c^2)       -0.0002512  0.0001065  -2.360 0.018320 *  
length_c             -0.1180018  0.0101822 -11.589  &lt; 2e-16 ***
shell_w_c             0.1497556  0.0051200  29.249  &lt; 2e-16 ***
diameter_c            0.0230993  0.0130173   1.775 0.076052 .  
length_c:shell_w_c   -0.0013842  0.0007141  -1.938 0.052644 .  
length_c:diameter_c   0.0051125  0.0015577   3.282 0.001039 ** 
shell_w_c:diameter_c  0.0010126  0.0009031   1.121 0.262262    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.373 on 4165 degrees of freedom
Multiple R-squared:  0.473, Adjusted R-squared:  0.4719 
F-statistic: 415.4 on 9 and 4165 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Percebe-se que o modelo é significativo (passa no teste-F global com valor-p da ordem de e-16) e o coeficiente de determinação ajustado indica que aproximadamente 47.2% da variabilidade na resposta é explicada pelo modelo. Com <span class="math inline">\(\alpha = 5%\)</span>, percebemos que os coeficientes de <code>shell_w_c^2</code>, <code>diameter_c</code>, <code>length_c:shell_w_c</code> e <code>shell_w_c:diameter_c</code> não são significantes. Vamos considerar um modelo reduzido sem essas variáveis, exceto por <code>diameter_c</code>, uma vez que o princípio da hierarquia determina que, se <code>diameter_c</code> for removido, <code>diameter_c^2</code> também deve ser, porém o modelo considera <code>diameter_c^2</code> como estatisticamente significante, manteremos o termo linear.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># modelo reduzido</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>m1_red <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> <span class="fu">I</span>(length_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(diameter_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> diameter_c<span class="sc">*</span>length_c <span class="sc">+</span> shell_w_c  , <span class="at">data =</span> abalone)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># resumo do modelo reduzido </span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_red)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ I(length_c^2) + I(diameter_c^2) + diameter_c * 
    length_c + shell_w_c, data = abalone)

Residuals:
   Min     1Q Median     3Q    Max 
-7.833 -1.495 -0.438  1.023 16.440 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         12.3059159  0.0526763 233.614  &lt; 2e-16 ***
I(length_c^2)       -0.0022515  0.0005927  -3.799 0.000148 ***
I(diameter_c^2)     -0.0036096  0.0010585  -3.410 0.000656 ***
diameter_c           0.0476620  0.0127519   3.738 0.000188 ***
length_c            -0.1134712  0.0102098 -11.114  &lt; 2e-16 ***
shell_w_c            0.1219487  0.0038340  31.807  &lt; 2e-16 ***
diameter_c:length_c  0.0039313  0.0015081   2.607 0.009174 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.393 on 4168 degrees of freedom
Multiple R-squared:  0.4638,    Adjusted R-squared:  0.463 
F-statistic: 600.8 on 6 and 4168 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Todos os coeficientes são estatisiticamente significantes, o modelo reduzido é significativo pela estatística F e o coeficiente de determinação ajustado indica que aproximadamente 46.3% da variabilidade na resposta é explicada pelo modelo.</p>
<p>Vamos agora realizar o teste de hipótese a seguir: Ho: <span class="math inline">\(\beta_{33} = \beta_{13} = \beta_{23} = 0\)</span><br>
Ha: nem todos os coeficientes são nulos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># teste-F (comparação de modelos aninhados)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1_red, m1_quant, <span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: age ~ I(length_c^2) + I(diameter_c^2) + diameter_c * length_c + 
    shell_w_c
Model 2: age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + length_c * 
    shell_w_c + diameter_c * length_c + diameter_c * shell_w_c
  Res.Df   RSS Df Sum of Sq      F    Pr(&gt;F)    
1   4168 23870                                  
2   4165 23458  3    411.91 24.379 1.237e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>O teste indica que podemos rejeitar a hipótese nula, logo não podemos concluir que os três coeficientes são nulos. Vamos tentar incluir <code>shell_w_c^2</code> no modelo reduzido e avaliar novamente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># modelo reduzido</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>m1_red_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> <span class="fu">I</span>(length_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(diameter_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(shell_w_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span>  diameter_c<span class="sc">*</span>length_c <span class="sc">+</span> shell_w_c , <span class="at">data =</span> abalone)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co"># resumo do modelo reduzido </span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_red_2)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + 
    diameter_c * length_c + shell_w_c, data = abalone)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.5092 -1.4685 -0.3967  1.0059 16.5177 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          1.253e+01  5.896e-02 212.490  &lt; 2e-16 ***
I(length_c^2)       -2.417e-03  5.884e-04  -4.108 4.07e-05 ***
I(diameter_c^2)     -3.429e-03  1.051e-03  -3.264  0.00111 ** 
I(shell_w_c^2)      -4.148e-04  5.079e-05  -8.166 4.19e-16 ***
diameter_c           2.453e-02  1.297e-02   1.892  0.05854 .  
length_c            -1.197e-01  1.016e-02 -11.785  &lt; 2e-16 ***
shell_w_c            1.498e-01  5.111e-03  29.314  &lt; 2e-16 ***
diameter_c:length_c  4.193e-03  1.497e-03   2.802  0.00511 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.374 on 4167 degrees of freedom
Multiple R-squared:  0.4722,    Adjusted R-squared:  0.4713 
F-statistic: 532.6 on 7 and 4167 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Incluindo novamente <code>shell_w_c^2</code>, percebemos que o termo agora recebe p-valor muito baixo, indicando ser significante. Percebemos nesse ultimo modelo tambem que <code>diameter_c</code> voltou a ser considerado não significativo (ainda que esteja no limiar), porém o termo de interação <code>diameter_c:length_c</code> e o termo quadrático <code>diameter_c^2</code> ainda são significativos. Esse modelo reduzido também é significativo pela estatística F e o coeficiente de determinação ajustado indica que aproximadamente 47.2% da variabilidade na resposta é explicada pelo modelo. Vamos compará-lo ao modelo <code>m1_quant</code> agora, com as seguintes hipóteses:</p>
<p>Ho: <span class="math inline">\(\beta_{13} = \beta_{23} = 0\)</span><br>
Ha: nem todos os coeficientes são nulos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># teste-F (comparação de modelos aninhados)</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1_red_2, m1_quant, <span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + diameter_c * 
    length_c + shell_w_c
Model 2: age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + length_c * 
    shell_w_c + diameter_c * length_c + diameter_c * shell_w_c
  Res.Df   RSS Df Sum of Sq      F  Pr(&gt;F)  
1   4167 23494                              
2   4165 23458  2    35.961 3.1926 0.04117 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Ainda não podemos inferir, com 95% de confiança, que os coeficientes são nulos (rejeita-se a hipótese nula). Vamos adicionar novamente o termo <code>length_c:shell_w_c</code>, pois ele possui menor p-valor em <code>m1_quant</code> do que <code>shell_w_c:diameter_c</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># modelo reduzido</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>m1_red_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> <span class="fu">I</span>(length_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(diameter_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(shell_w_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span>  diameter_c<span class="sc">*</span>length_c <span class="sc">+</span> shell_w_c<span class="sc">*</span>length_c , <span class="at">data =</span> abalone)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># resumo do modelo reduzido </span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_red_3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + 
    diameter_c * length_c + shell_w_c * length_c, data = abalone)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.6914 -1.4786 -0.3987  1.0149 16.5932 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         12.5352978  0.0590032 212.451  &lt; 2e-16 ***
I(length_c^2)       -0.0023037  0.0005903  -3.903 9.66e-05 ***
I(diameter_c^2)     -0.0036080  0.0010530  -3.427 0.000617 ***
I(shell_w_c^2)      -0.0002155  0.0001016  -2.122 0.033922 *  
diameter_c           0.0244792  0.0129594   1.889 0.058972 .  
length_c            -0.1186703  0.0101650 -11.674  &lt; 2e-16 ***
shell_w_c            0.1494173  0.0051113  29.233  &lt; 2e-16 ***
diameter_c:length_c  0.0046934  0.0015122   3.104 0.001924 ** 
length_c:shell_w_c  -0.0006514  0.0002877  -2.264 0.023598 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.373 on 4166 degrees of freedom
Multiple R-squared:  0.4729,    Adjusted R-squared:  0.4719 
F-statistic: 467.1 on 8 and 4166 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>O modelo é significante pela estatística F e o coeficiente de determinação ajustado indica que aproximadamente 47.2% da variabilidade na resposta é explicada por ele. Percebe-se que a tabela ANOVA indica que apenas <code>diameter_c</code> é não significante agora.</p>
<p>Realizando o teste de hipótese ao comparar com <code>m1_quant</code>: Ho: <span class="math inline">\(\beta_{23} = 0\)</span><br>
Ha: <span class="math inline">\(\beta_{23} \neq 0\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># teste-F (comparação de modelos aninhados)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1_red_3, m1_quant, <span class="at">test=</span><span class="st">"F"</span>)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + diameter_c * 
    length_c + shell_w_c * length_c
Model 2: age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + length_c * 
    shell_w_c + diameter_c * length_c + diameter_c * shell_w_c
  Res.Df   RSS Df Sum of Sq      F Pr(&gt;F)
1   4166 23465                           
2   4165 23458  1    7.0802 1.2571 0.2623</code></pre>
</div>
</div>
<p>Não podemos rejeitar a hipótese nula. Aceitamos-a, portanto, e temos um modelo reduzido da forma <span class="math display">\[
  E[age] = \beta_0 + \beta_1 length + \beta_{11}length^2  + \beta_2 diameter + \beta_{22} diameter^2 +  \beta_3 shell_w + \beta_{33} shell_w^2 + \beta_{12} length \cdot diameter + \beta_{13} length \cdot shell_w
\]</span> Podemos prosseguir com a análise de resíduos para avaliar a validade do modelo:</p>
<div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constrói tabela com dados do modelo `m_red`</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>abalone_m1_quant_red_3_data <span class="ot">&lt;-</span> abalone <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># inclui coluna com valores ajustados</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fitted =</span> m1_red_3<span class="sc">$</span>fit) <span class="sc">%&gt;%</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">resid =</span> m1_red_3<span class="sc">$</span>res)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Gera gráficos dos resíduos:</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(abalone_m1_quant_red_3_data, <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> resid)) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"gráfico de resíduos: modelo m1_red_3"</span>) <span class="sc">+</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"resíduos"</span>, <span class="at">x =</span> <span class="st">"resposta ajustada (age)"</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico de quantis</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(abalone_m1_quant_red_3_data, <span class="fu">aes</span>(<span class="at">sample =</span> resid)) <span class="sc">+</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"gráfico de quantis normais"</span>) <span class="sc">+</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"quantis amostrais"</span>, <span class="at">x =</span> <span class="st">"quantis teóricos (dist. normal)"</span>) </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="GED16_AULA07_Pratica_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="GED16_AULA07_Pratica_files/figure-html/unnamed-chunk-19-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>O gráfico de resíduos indica um efeito cone, com o aumento da variância com o aumento de age. Conferiremos essa hipótese a seguir com o teste de Breusch-Pagan. Porém, não parece existir tendência de variação sistemática nos resíduos. O gráfico de quantis sugere desvio da normalidade, pequeno na cauda esquerda e mais acentuado na cauda direita. Esse desvio provavelmente não causará grandes problemas, mas é possível que transformações de variáveis ajudem a reduzir a fuga de normalidade.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de Homoscedasticidade de Breusch-Pagan</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ho: sigma^2  = cte</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Ha: sigma^2 != cte</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(m1_red_3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  m1_red_3
BP = 263.31, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de Homoscedasticidade de Breusch-Pagan</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ho: sigma^2  = cte</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Ha: sigma^2 != cte</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="fu">bptest</span>(m1_red_3)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  m1_red_3
BP = 263.31, df = 8, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>De fato, os testes rejeitam as hipóteses nulas e confirmam as violações nas hipóteses de homoscedasticidade e de normalidade.</p>
</section>
<section id="inclusão-da-variável-categórica" class="level4">
<h4 class="anchored" data-anchor-id="inclusão-da-variável-categórica">1.2)Inclusão da Variável Categórica</h4>
<p>Prosseguiremos adicionando a variável categórica <code>sex</code> ao modelo reduzido <code>m1_red_3</code>:¨</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># modelo que inclui variável explicativa qualitativa `cylinder`</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>m_quali <span class="ot">&lt;-</span> <span class="fu">lm</span>(age <span class="sc">~</span> <span class="fu">I</span>(length_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(diameter_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(shell_w_c<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span>  diameter_c<span class="sc">*</span>length_c <span class="sc">+</span> shell_w_c<span class="sc">*</span>length_c  <span class="sc">+</span> sex, <span class="at">data =</span> abalone)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># resumo do modelo</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_quali)</span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ I(length_c^2) + I(diameter_c^2) + I(shell_w_c^2) + 
    diameter_c * length_c + shell_w_c * length_c + sex, data = abalone)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.5733 -1.4657 -0.3800  0.9868 16.5350 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         12.7701740  0.0800903 159.447  &lt; 2e-16 ***
I(length_c^2)       -0.0022048  0.0005875  -3.753 0.000177 ***
I(diameter_c^2)     -0.0031904  0.0010498  -3.039 0.002388 ** 
I(shell_w_c^2)      -0.0001867  0.0001012  -1.846 0.065010 .  
diameter_c           0.0176553  0.0129331   1.365 0.172287    
length_c            -0.1126790  0.0101526 -11.099  &lt; 2e-16 ***
shell_w_c            0.1417059  0.0052193  27.150  &lt; 2e-16 ***
sexI                -0.7269988  0.1113484  -6.529 7.41e-11 ***
sexM                -0.1527700  0.0892594  -1.712 0.087058 .  
diameter_c:length_c  0.0041116  0.0015074   2.728 0.006407 ** 
length_c:shell_w_c  -0.0005113  0.0002871  -1.781 0.074989 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.361 on 4164 degrees of freedom
Multiple R-squared:  0.4785,    Adjusted R-squared:  0.4772 
F-statistic: 382.1 on 10 and 4164 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<hr>
</section>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>